# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abe0767f986adadb1256927302553afd0b051f70a6059610e13e7ac94bc50d0a671b6d0244951c5c625ced31e09a2ee73bf337796e370739cd8e2ed24c220042

test:
  secret_key_base: 9709a458133f009b71e63485c09c680c6612f1e39ba9415ea034b30bc7121ef684ceb2fd72a83f3567f27f99ef092d72458e5790f96810cf34a0b7b1a906965a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 6c341469b9663a3791308bc21b5fad9cfc67eb1b7d7c2b581c04325a94b11c4ef7725bba54aa5b8eb367aa3b89f874ba36ef0db5fc3d855706e3364293331609
